version: 2.1

jobs:
  build_backend:
    working_directory: ~/project/backend
    docker:
      - image: alpine:3.12
    steps:
      - checkout:
          path: ~/project
      - run:
          name: The First Step
          command: |
            echo 'Hello Backend!'
            ls
  build_frontend:
    working_directory: ~/project/frontend
    docker:
      - image: alpine:3.12
    steps:
      - checkout:
          path: ~/project
      - run:
          name: The First Step
          command: |
            echo 'Hello Frontend!'
            ls

workflows:
  version: 2
  build:
    jobs:
      - build_backend
      - build_frontend
